services:
  postgres:
    image: postgres:16
    container_name: find_your_job_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: findjob
      POSTGRES_PASSWORD: findjob123
      POSTGRES_DB: find_your_job
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: