package users

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/lib/pq"
)

// PostgresUserRepo implements UserRepository backed by PostgreSQL.
type PostgresUserRepo struct {
	db *sql.DB
}

// NewPostgresUserRepo creates a PostgresUserRepo with the given database connection.
func NewPostgresUserRepo(db *sql.DB) *PostgresUserRepo {
	return &PostgresUserRepo{db: db}
}

// ── Create ──────────────────────────────────────────

// Create inserts a new user row.
// The id, created_at, and updated_at are generated by PostgreSQL and
// written back into the provided User struct.
func (r *PostgresUserRepo) Create(ctx context.Context, user *User) error {
	const query = `
		INSERT INTO users (email, password_hash, role, name, is_active)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, created_at, updated_at
	`

	row := r.db.QueryRowContext(ctx, query,
		user.Email,
		user.PasswordHash,
		user.Role,
		user.Name,
		user.IsActive,
	)

	err := row.Scan(&user.ID, &user.CreatedAt, &user.UpdatedAt)
	if err != nil {
		if isUniqueViolation(err) {
			return ErrEmailAlreadyExists
		}
		return fmt.Errorf("create user: %w", err)
	}

	return nil
}

// ── FindByID ────────────────────────────────────────

// FindByID returns the user with the given UUID, or ErrUserNotFound.
func (r *PostgresUserRepo) FindByID(ctx context.Context, id string) (*User, error) {
	const query = `
		SELECT id, email, password_hash, role, name, is_active, created_at, updated_at
		FROM users
		WHERE id = $1
	`

	user := &User{}
	err := r.db.QueryRowContext(ctx, query, id).Scan(
		&user.ID,
		&user.Email,
		&user.PasswordHash,
		&user.Role,
		&user.Name,
		&user.IsActive,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("find user by id: %w", err)
	}

	return user, nil
}

// ── FindByEmail ─────────────────────────────────────

// FindByEmail returns the user with the given email, or ErrUserNotFound.
func (r *PostgresUserRepo) FindByEmail(ctx context.Context, email string) (*User, error) {
	const query = `
		SELECT id, email, password_hash, role, name, is_active, created_at, updated_at
		FROM users
		WHERE email = $1
	`

	user := &User{}
	err := r.db.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.Email,
		&user.PasswordHash,
		&user.Role,
		&user.Name,
		&user.IsActive,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("find user by email: %w", err)
	}

	return user, nil
}

// ── Update ──────────────────────────────────────────

// Update modifies the user's mutable fields (name, role, is_active).
// The updated_at timestamp is set by PostgreSQL.
func (r *PostgresUserRepo) Update(ctx context.Context, user *User) error {
	const query = `
		UPDATE users
		SET name = $2, role = $3, is_active = $4, updated_at = NOW()
		WHERE id = $1
		RETURNING updated_at
	`

	err := r.db.QueryRowContext(ctx, query,
		user.ID,
		user.Name,
		user.Role,
		user.IsActive,
	).Scan(&user.UpdatedAt)

	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrUserNotFound
		}
		return fmt.Errorf("update user: %w", err)
	}

	return nil
}

// ── Delete ──────────────────────────────────────────

// Delete removes a user by ID. Returns ErrUserNotFound if no row matched.
func (r *PostgresUserRepo) Delete(ctx context.Context, id string) error {
	const query = `DELETE FROM users WHERE id = $1`

	result, err := r.db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("delete user: %w", err)
	}

	rows, _ := result.RowsAffected()
	if rows == 0 {
		return ErrUserNotFound
	}

	return nil
}

// ── List ────────────────────────────────────────────

// List returns a paginated slice of users ordered by created_at DESC.
func (r *PostgresUserRepo) List(ctx context.Context, limit, offset int) ([]User, error) {
	const query = `
		SELECT id, email, password_hash, role, name, is_active, created_at, updated_at
		FROM users
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2
	`

	rows, err := r.db.QueryContext(ctx, query, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("list users: %w", err)
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(
			&u.ID, &u.Email, &u.PasswordHash, &u.Role, &u.Name,
			&u.IsActive, &u.CreatedAt, &u.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan user row: %w", err)
		}
		users = append(users, u)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate user rows: %w", err)
	}

	return users, nil
}

// ── Helpers ─────────────────────────────────────────

// isUniqueViolation checks whether err is a PostgreSQL unique-constraint violation.
func isUniqueViolation(err error) bool {
	var pqErr *pq.Error
	if errors.As(err, &pqErr) {
		return pqErr.Code == "23505" // unique_violation
	}
	return false
}
