package users

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

// PostgresCandidateProfileRepo implements CandidateProfileRepository backed by PostgreSQL.
type PostgresCandidateProfileRepo struct {
	db *sql.DB
}

// NewPostgresCandidateProfileRepo creates a PostgresCandidateProfileRepo.
func NewPostgresCandidateProfileRepo(db *sql.DB) *PostgresCandidateProfileRepo {
	return &PostgresCandidateProfileRepo{db: db}
}

// ── Create ──────────────────────────────────────────

// Create inserts a new candidate profile row.
// The id, created_at, and updated_at are generated by PostgreSQL.
func (r *PostgresCandidateProfileRepo) Create(ctx context.Context, profile *CandidateProfile) error {
	const query = `
		INSERT INTO candidate_profiles (
			user_id, phone, location, summary, experience_years,
			resume_url, linkedin_url, github_url, portfolio_url,
			preferred_remote, preferred_location, salary_min, salary_max
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		RETURNING id, created_at, updated_at
	`

	row := r.db.QueryRowContext(ctx, query,
		profile.UserID,
		profile.Phone,
		profile.Location,
		profile.Summary,
		profile.ExperienceYears,
		profile.ResumeURL,
		profile.LinkedinURL,
		profile.GithubURL,
		profile.PortfolioURL,
		profile.PreferredRemote,
		profile.PreferredLocation,
		profile.SalaryMin,
		profile.SalaryMax,
	)

	err := row.Scan(&profile.ID, &profile.CreatedAt, &profile.UpdatedAt)
	if err != nil {
		if isUniqueViolation(err) {
			return fmt.Errorf("%w: user %s already has a profile", ErrProfileNotFound, profile.UserID)
		}
		return fmt.Errorf("create candidate profile: %w", err)
	}

	return nil
}

// ── FindByID ────────────────────────────────────────

// FindByID returns the candidate profile with the given UUID.
func (r *PostgresCandidateProfileRepo) FindByID(ctx context.Context, id string) (*CandidateProfile, error) {
	const query = `
		SELECT id, user_id, phone, location, summary, experience_years,
		       resume_url, linkedin_url, github_url, portfolio_url,
		       preferred_remote, preferred_location, salary_min, salary_max,
		       created_at, updated_at
		FROM candidate_profiles
		WHERE id = $1
	`

	profile, err := scanProfile(r.db.QueryRowContext(ctx, query, id))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrProfileNotFound
		}
		return nil, fmt.Errorf("find profile by id: %w", err)
	}

	return profile, nil
}

// ── FindByUserID ────────────────────────────────────

// FindByUserID returns the candidate profile for the given user ID.
func (r *PostgresCandidateProfileRepo) FindByUserID(ctx context.Context, userID string) (*CandidateProfile, error) {
	const query = `
		SELECT id, user_id, phone, location, summary, experience_years,
		       resume_url, linkedin_url, github_url, portfolio_url,
		       preferred_remote, preferred_location, salary_min, salary_max,
		       created_at, updated_at
		FROM candidate_profiles
		WHERE user_id = $1
	`

	profile, err := scanProfile(r.db.QueryRowContext(ctx, query, userID))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrProfileNotFound
		}
		return nil, fmt.Errorf("find profile by user id: %w", err)
	}

	return profile, nil
}

// ── Update ──────────────────────────────────────────

// Update modifies the mutable fields of a candidate profile.
func (r *PostgresCandidateProfileRepo) Update(ctx context.Context, profile *CandidateProfile) error {
	const query = `
		UPDATE candidate_profiles
		SET phone = $2, location = $3, summary = $4, experience_years = $5,
		    resume_url = $6, linkedin_url = $7, github_url = $8, portfolio_url = $9,
		    preferred_remote = $10, preferred_location = $11,
		    salary_min = $12, salary_max = $13,
		    updated_at = NOW()
		WHERE id = $1
		RETURNING updated_at
	`

	err := r.db.QueryRowContext(ctx, query,
		profile.ID,
		profile.Phone,
		profile.Location,
		profile.Summary,
		profile.ExperienceYears,
		profile.ResumeURL,
		profile.LinkedinURL,
		profile.GithubURL,
		profile.PortfolioURL,
		profile.PreferredRemote,
		profile.PreferredLocation,
		profile.SalaryMin,
		profile.SalaryMax,
	).Scan(&profile.UpdatedAt)

	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrProfileNotFound
		}
		return fmt.Errorf("update candidate profile: %w", err)
	}

	return nil
}

// ── Scanner ─────────────────────────────────────────

// scanProfile scans a single candidate_profiles row into a CandidateProfile.
func scanProfile(row *sql.Row) (*CandidateProfile, error) {
	var (
		p                 CandidateProfile
		phone, location   sql.NullString
		summary           sql.NullString
		resumeURL         sql.NullString
		linkedinURL       sql.NullString
		githubURL         sql.NullString
		portfolioURL      sql.NullString
		preferredLocation sql.NullString
		salaryMin         sql.NullInt64
		salaryMax         sql.NullInt64
	)

	err := row.Scan(
		&p.ID, &p.UserID,
		&phone, &location, &summary, &p.ExperienceYears,
		&resumeURL, &linkedinURL, &githubURL, &portfolioURL,
		&p.PreferredRemote, &preferredLocation,
		&salaryMin, &salaryMax,
		&p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	p.Phone = nullString(phone)
	p.Location = nullString(location)
	p.Summary = nullString(summary)
	p.ResumeURL = nullString(resumeURL)
	p.LinkedinURL = nullString(linkedinURL)
	p.GithubURL = nullString(githubURL)
	p.PortfolioURL = nullString(portfolioURL)
	p.PreferredLocation = nullString(preferredLocation)
	p.SalaryMin = nullInt(salaryMin)
	p.SalaryMax = nullInt(salaryMax)

	return &p, nil
}

// ── Helpers ─────────────────────────────────────────

func nullString(ns sql.NullString) *string {
	if ns.Valid {
		return &ns.String
	}
	return nil
}

func nullInt(ni sql.NullInt64) *int {
	if ni.Valid {
		v := int(ni.Int64)
		return &v
	}
	return nil
}
